files:
  - source: /src/main/resources/lang/messages_fallback.yml
    translation: /crowdin/%locale_with_underscore%/messages.yml
  - source: /webui/src/**/locale/zh-CN.ts
    translation: /crowdin-webui/%original_path%/%locale%.ts
